[package]
name = "gazelle"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }

[[bin]]
name = "gz"
path = "rust/main.rs"

[lib]
path = "rust/lib.rs"
crate-type = ["cdylib"]
