name: Development

on:
  push:
    branches: dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: "Development"

    steps: 
      - name: Print Message
        run: echo "Simulating build..."