name: Development CI

on:
  push:
    branches: dev

jobs:
  build:
    name: Build .NET Project
    runs-on: ubuntu-latest
    environment: 
      name: Development

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Build Project
        run: dotnet build
