name: Development

on:
  push:
    branches: dev

jobs:
  name: Build
  runs-on: ubuntu-latest
  environment:
    name: "Development"

  build:
    steps: 
      - name: Print Message
        run: echo "Simulating build..."