name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

defaults:
  run:
    shell: pwsh

jobs:
  setup: 
    name: Setup
    runs-on: Ubuntu-Latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

  ci:
    name: CI
    runs-on: Ubuntu-Latest
    needs: [setup]

    steps:
      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet fantomas . --check

      - name: Test
        run: dotnet test
