name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

defaults:
  run:
    shell: pwsh

jobs:
  ci:
    name: CI
    runs-on: Ubuntu-Latest
    strategy:
      matrix:
        version: ['3.11', '3.12']
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version}}
    
      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run Test Suite
        run: poetry run pytest
