name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build
    runs-on: Ubuntu-Latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod