name: Production

on:
  push:
    branches: main
    
jobs:
  deploy-static-web-app:
    name: Publish calcpad.io
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.publish-to-azure-swa.outputs.static_web_app_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        id: publish-to-azure-swa
        with:
          azure_static_web_apps_api_token: ${{ secrets.CALCPAD_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          api_location: ""
          app_location: "/projects/calcpad/www"
          output_location: ""
          skip_api_build: true