name: Production

on:
  push:
    branches: main
    
jobs:
  deploy-static-web-app:
    name: Publish calcpad.io
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.publish-to-azure-swa.outputs.static_web_app_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Fortress
        run: |
          cd ./projects/fortress
          npm ci
          npm run build

      - name: Build and Deploy Calcpad
        uses: Azure/static-web-apps-deploy@v1
        id: publish-to-azure-swa
        with:
          azure_static_web_apps_api_token: ${{ secrets.CALCPAD_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          api_location: ""
          app_location: "/projects/calcpad/www"
          output_location: ""
          skip_api_build: true