name: Production

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: pwsh

jobs:
  ci:
    name: CI
    runs-on: Ubuntu-Latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x.x"

      - name: Restore Project
        run: ./Setup.ps1

      - name: Check Code Formatting
        run: dotnet fantomas . --check

      - name: Run Test Suite
        run: dotnet test

  publish: 
    name: Publish To NuGet Gallery
    environment: Production
    runs-on: Ubuntu-Latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Publish
        run: dotnet publish "./src" -c "Release"

      - name: Push
        run: |
          dotnet nuget push src/bin/Release/*.nupkg `
            --api-key ${{ secrets.NUGET_KEY }} `
            --source "https://api.nuget.org/v3/index.json" `
            --skip-duplicate