name: Production

on:
  push:
    branches: main

jobs:
  build-fortress:
    name: Build Fortress
    runs-on: ubuntu-latest
    environment: Production

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore Projects
        run: ./scripts/Restore-Project.ps1

      - name: Check Code Formatting
        run: |
          Set-Location "./projects"
          dotnet fantomas "." --recurse --check

      - name: Run Test Suite
        run: |
          Set-Location "./projects"
          dotnet test

      - name: Build Projects
        run: |
          Set-Location "./projects"
          dotnet build --configuration "Release"

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./projects/Fortress/bin/Release/*.nupkg

  publish-to-nuget-gallery:
    name: Publish to NuGet Gallery
    runs-on: ubuntu-latest
    needs: build-fortress

    env:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
      - name: Download NuGet Artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package

      - name: Publish to NuGet Gallery
        shell: pwsh
        run: |
          dotnet nuget push *.nupkg ` 
            --api-key $Env:NUGET_KEY `
            --source "https://api.nuget.org/v3/index.json"