name: Production

on:
  push:
    branches: main
    
jobs:
  build-fortress:
    name: Build Fortress
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        shell: pwsh
        working-directory: projects

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Install .NET Tools
        run: dotnet tool restore

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Packages.
        run: |
          cd Fortress
          npm ci