name: Development

on:
  push:
    branches: dev

jobs:
  build-fortress:
    name: Build Fortress
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore Projects
        run: ./scripts/Restore-Project.ps1

      - name: Check Code Formatting
        run: |
          Set-Location "./projects"
          dotnet fantomas "." --recurse --check

      - name: Run Test Suite
        run: |
          Set-Location "./projects"
          dotnet test

      - name: Build .NET Projects
        run: |
          Set-Location "./projects"
          dotnet build --configuration "Release"
      
      - name: Invoke Fable Transpiler
        run: |
          Set-Location "./projects/Fortress"
          dotnet fable --lang javascript
          Get-Content "./Interop/JS.fs.js"
          # npm run build
