name: Production

on:
  push:
    branches: main

jobs:
  build-fortress:
    name: Build Fortress
    runs-on: ubuntu-latest
    environment: Production

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore Projects
        run: ./scripts/Restore-Project.ps1

      - name: Check Code Formatting
        run: |
          Set-Location "./projects"
          dotnet fantomas "." --recurse --check

      - name: Build Projects
        run: |
          Set-Location "./projects"
          dotnet build

      - name: Run Test Suite
        run: |
          Set-Location "./projects"
          dotnet test
